# application.properties
spring.application.name=NextIndie

# PostgreSQL Configuration (Docker)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# Server
server.port=8080

# IGDB
igdb.api.base-url=https://api.igdb.com/v4
igdb.api.token-url=https://id.twitch.tv/oauth2/token
igdb.api.client-id=${IGDB_CLIENT_ID:rvekg7tgo00ze04zw7xdu4scipp556}
igdb.api.client-secret=${IGDB_CLIENT_SECRET:8qat6hv4j3j97gaigghbqcjrh666t7}
