# ============================================
# CONFIGURACIÓN BASE DE DATOS POSTGRESQL
# ============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/nextindie_db
spring.datasource.username=postgres
spring.datasource.password=tu_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Schema por defecto
spring.jpa.properties.hibernate.default_schema=nextindie

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Servidor
server.port=8080

# JWT
jwt.secret=sgHk5$XmY9>&!WzPKeP8bAqJ7rUXfxvzLu2ErWtNmBhr6UaVoJ3gTQ4sZr6pWlx
jwt.expiration=86400000

# CORS (para desarrollo)
cors.allowed-origins=http://localhost:4200